config/routes.rb
Rails.application.routes.draw do
  resources :books
  devise_for :users
  get 'dashboard', to: 'pages#dashboard'
  root 'pages#home'

  post '/buy/:id', to: 'transactions#create', as: :buy
  get '/pickup/:guid', to: 'transactions#pickup', as: :pickup
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    user ||= User.new # guest user (not logged in)
    can :read, :all
    can :manage, Book do |book|
      book.try(:user) == user
    end
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/ryanb/cancan/wiki/Defining-Abilities
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user
  has_attached_file :image
  has_attached_file :resource
  has_many :sales


  # Validation ensures a valid image
  validates_attachment_content_type :image,
  content_type: /^image\/(png|gif|jpeg)/,
	message: "Only images allowed"
  # Validation ensures a valid e-book type for resource
  validates_attachment_content_type :resource,
		content_type: ['application/pdf'],
		message: "Only pdf allowed"

  # Validation ensures image is present
  validates :image, attachment_presence: true
  # Validation ensures resource is present
  validates :resource, attachment_presence: true

  # Books should cost 99 cents or more
  validates_numericality_of :price,
    greater_than: 99, message: "Must be atleast 99 cents."
end

app/models/sale.rb
class Sale < ApplicationRecord
  before_create :populate_guid
  belongs_to :book
  belongs_to :seller, class_name: 'User'
  belongs_to :buyer, class_name: 'User'

  include AASM

  aasm column: 'state' do
    state :pending, initial: true
    state :processing
    state :finished
    state :errored

    event :process, after: :charge_card do
      transitions from: :pending, to: :processing
    end

    event :finish do
      transitions from: :processing, to: :finished
    end

    event :fail do
      transitions from: :processing, to: :errored
    end
  end

  def charge_card

    begin
      save!
      charge = Stripe::Charge.create(
        amount: self.amount,
        currency: 'usd',
        card: self.stripe_token,
        description: "Book Sale")

        self.update(stripe_id: charge.id)
        self.finish!
    rescue Stripe::CardError => e
      self.update_attributes(error: e.message)
      self.fail!
    end

  end

  private
  def populate_guid
    self.guid = SecureRandom.uuid()
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :books
  has_many :sales, class_name: 'Sale', foreign_key: 'seller'
  has_many :purchases, class_name: 'Sale', foreign_key: 'buyer'
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  # Cancan throws an Error when a user is editing a resource that they are not
  # permited. Here we catch the error and give them a nice message.
  rescue_from CanCan::AccessDenied do |exception|
    redirect_to books_path, notice: "You are not authorized to access this area"
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :set_book, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [:edit, :update, :new, :create, :destroy]

  # GET /books
  # GET /books.json
  def index
    @books = Book.where(availability: true)
  end

  # GET /books/1
  # GET /books/1.json
  def show
  end

  # GET /books/new
  def new
    @book = Book.new
  end

  # GET /books/1/edit
  def edit
    # books can only be managed by the owner
    authorize! :manage, @book
  end

  # POST /books
  # POST /books.json
  def create
    @book = current_user.books.new(book_params)

    respond_to do |format|
      if @book.save
        format.html { redirect_to @book, notice: 'Book was successfully created.' }
        format.json { render :show, status: :created, location: @book }
      else
        format.html { render :new }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /books/1
  # PATCH/PUT /books/1.json
  def update
    # books can only be managed by the owner
    authorize! :manage, @book
    respond_to do |format|
      if @book.update(book_params)
        format.html { redirect_to @book, notice: 'Book was successfully updated.' }
        format.json { render :show, status: :ok, location: @book }
      else
        format.html { render :edit }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /books/1
  # DELETE /books/1.json
  def destroy
    @book.destroy
    respond_to do |format|
      format.html { redirect_to books_url, notice: 'Book was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_book
      @book = Book.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def book_params
      params.require(:book).permit(:name, :author, :description, :price, :availability, :image, :resource)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  before_action :authenticate_user!, only: :dashboard
  def home
    redirect_to dashboard_path if current_user
    @books = Book.last(4)
  end

  def dashboard
    @offered_books = current_user.books
    @purchased = Sale.where(buyer: current_user)
    @sales = Sale.where(seller: current_user)
  end
end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController
  def create
    book = Book.find_by!(id: params[:id])
    @sale = book.sales.create(
      amount: book.price,
      seller: book.user,
      buyer: current_user,
			stripe_token: params[:stripeToken])
    @sale.process!

    if @sale.finished?
      redirect_to pickup_url(guid: @sale.guid)
    else
      redirect_to book_path(book), notice: @error
    end
  end

  def pickup
    @sale = Sale.find_by!(guid: params[:guid])
    @book = @sale.book
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/books/_book.html.erb
<div class="col-md-3">
  <div class="thmbnail">
    <%= link_to(book) do %>
      <%= image_tag book.image.url(:original), class: "img-responsive" %>
    <% end %>
    <div class="caption">
      <p><strong><%=link_to book.name, book %></strong></p>
      <p><%= number_to_currency(book.price.to_f / 100) %></p>
    </div>
  </div>
</div>

app/views/books/_form.html.erb
<%= simple_form_for(@book, html: { class: "form-signin" }) do |f| %>
  <%= f.error_notification %>

  <%= f.input :name, required: true, label: false,  placeholder: "Book Title",
      input_html: { class: "form-control" } %>
  <%= f.input :author, required: true, label: false, placeholder: "Author",
      input_html: { class: "form-control" } %>
  <%= f.input :description, required: false, label: false, placeholder: "Description",
      input_html: { class: "form-control" }, rows: 7 %>
  <%= f.input :price, required: true, label: false, placeholder: "Price", hint: "*Price in cents",
      input_html: { class: "form-control" } %>

  <%= f.input :image %>
  <%= f.input :resource %>

  <%= f.input :availability, required: false %>



  <%= f.button :submit, class: "btn btn-primary btn-block" %>

<% end %>

app/views/books/edit.html.erb
<h1 class="text-center">Editing Book</h1>

<%= render 'form', book: @book %>

<%= link_to 'Show', @book %> |
<%= link_to 'Back', books_path %>

app/views/books/index.html.erb
<div class="row">
  <%= render @books %>
</div>

app/views/books/new.html.erb
<h1 class="text-center">New Book</h1>

<%= render 'form', book: @book %>

<%= link_to 'Back', books_path %>

app/views/books/show.html.erb
<div class="row">
  <div class="col-md-6">
    <%= image_tag @book.image.url(:original), class: "img-responsive" %>
  </div>

  <div class="col-md-6">
    <div class="page-header">
      <h2><%= @book.name %><small> by <%= @book.author %></small></h2>
    </div>
    <p class="justify"><%= @book.description %></p>
    <h4 class="text-right"><%= number_to_currency(@book.price.to_f / 100) %></h4>

    <% if current_user %>
      <%= form_tag buy_path(@book.id) do %>
        <script
          src="https://checkout.stripe.com/checkout.js" class="stripe-button"
          data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
          data-amount="<%= @book.price %>"
          data-name="Book Box"
          data-description="<%= @book.name %>"
          data-email="<%= current_user.email %>"
          data-locale="auto">
        </script>
      <% end %>
    <% end %>
  </div>

</div>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-default navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <%= link_to "Book Box", root_path, class: "navbar-brand" %>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
          <ul class="nav navbar-nav">
            <% if current_user %>
              <li><%= link_to "Dashboard", dashboard_path %></li>
              <li><%= link_to "New Book", new_book_path %></li>
            <% end %>
          </ul>
          <ul class="nav navbar-nav navbar-right">
            <li><%= link_to "Books", books_path %></li>
            <% if current_user %>
              <li><%= link_to "Edit Profile", edit_user_registration_path %></li>
              <li><%= link_to "Log out", destroy_user_session_path, method: :delete %></li>
            <% else %>
              <li><%= link_to "Log in", new_user_session_path %></li>
            <% end %>
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BookBox</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <%= render 'layouts/navbar' %>

  <body>

    <% flash.each do |type, message| %>
        <div class="alert alert-info fade-in">
          <button class="close" data-dismiss="alert">×</button>
          <%= message %>
        </div>
    <% end %>

    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/pages/_books.html.erb
<table class="table table-condensed">
  <thead>
    <tr>
      <th>ID</th>
      <th>Name</th>
      <th></th>
      <th class="text-center">Available?</th>
    </tr>
  </thead>
  <tbody>
    <% @offered_books.each do |book| %>
    <tr>
      <th><%= book.id %></th>
      <td><%= link_to book.name, book_path(book) %></td>
      <td><%= link_to "Edit", edit_book_path(book)%></td>
      <td class="text-center">
        <% if book.availability %>
          <i class="fa fa-check" aria-hidden="true"></i>
        <% else %>
          <i class="fa fa-times" aria-hidden="true"></i>
        <% end %>
      </td>
    </tr>
    <% end %>
  </tbody>
</table>

app/views/pages/_purchased.html.erb
<table class="table table-condensed">
  <thead>
    <tr>
      <th>Name</th>
      <th>Date</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% @purchased.each do |sale| %>
    <tr>
      <td><%= link_to sale.book.name, book_path(sale.book) %></td>
      <td><%= time_ago_in_words(sale.created_at) %> ago</td>
      <td><%= link_to "Download", sale.book.resource.url, class: "btn btn-primary btn-sm" %></td>
    </tr>
    <% end %>
  </tbody>
</table>

app/views/pages/_sales.html.erb
<table class="table table-condensed">
  <thead>
    <tr>
      <th>Name</th>
      <th>Date</th>
      <th>Buyer</th>
    </tr>
  </thead>
  <tbody>
    <% @sales.each do |sale| %>
    <tr>
      <td><%= link_to sale.book.name, book_path(sale.book) %></td>
      <td><%= time_ago_in_words(sale.created_at) %> ago</td>
      <td><%= sale.buyer.email %></td>
    </tr>
    <% end %>
  </tbody>
</table>

app/views/pages/dashboard.html.erb
<div class="row">
  <div class="col-md-4">
    <h3 class="text-center">
      Books
      <%= link_to "New Book", new_book_path, class: "btn btn-primary btn-sm pull-right" %>
    </h3>
    <%= render 'books' %>
  </div>
  <div class="col-md-4">
    <h3 class="text-center">
      Purchased
    </h3>
    <%= render 'purchased' %>
  </div>
  <div class="col-md-4">
    <h3 class="text-center">
      Sales
    </h3>
    <%= render 'sales' %>
  </div>
</div>

app/views/pages/home.html.erb
<div class="jumbotron">
  <h1>Welcome to our store.</h1>
  <h2>Independent ebooks from around the globe. Register to start buying or selling now!</h2>
  <%= link_to "Register", new_user_registration_path, class: "btn btn-primary" %>
  <%= link_to "Books", books_path, class: "btn btn-primary" %>
</div>

<div class="row">
	<%= render @books %>
</div>

app/views/transactions/pickup.html.erb
<div class="row text-center">
	<br>
	<h1>Congratulations! </h1>
	<br>
	<h3>Thanks for buying <i>" <%= @sale.book.name %> "</i> <br>
	Here is the <%= link_to "download", @book.resource.url  %> link. </h3>
</div>